name: lighthouse-impact

on: pull_request_target

jobs:
  lighthouse-impact:
    runs-on: ubuntu-latest
    name: lighthouse impact
    env:
      CI: true
    steps:
      - name: Setup git
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: "14.17"
      - name: npm install
        run: npm install
      - name: Report lighthouse impact
        run: node ./.github/workflows/lighthouse-impact/report-lighthouse-impact.js
        env:
          GITHUB_TOKEN: ${{ secrets.LIGHTHOUSE_GITHUB_TOKEN }}
